### ISSUE TITLE
Framework 4.0.30319

### ISSUE THREAD

**Issue by Ya-Block** [marco-calautti/Rainbow#27]
when i open the exe, i get:
![image](https://github.com/marco-calautti/Rainbow/assets/146646463/75c7730f-9648-4478-98a6-1136dff9969f)
i used a hex editor to change the framework version to possibly fix it, but no, i get the same error message

**Comment by marco-calautti** [comment]
Well, the message says it clearly. You do not have the right version of the .NET Framework installed for it to run. Did you try installing it?

**Comment by Ya-Block** [comment]
Framework 4.0.30319 dosen't exist

**Comment by marco-calautti** [comment]
I would say any framework version 4 should be fine

**Comment by Ya-Block** [comment]
i have framework 4.8.1 and it dosent work

**Comment by marco-calautti** [comment]
I am on Windows 11 and Rainbow starts just fine. I never installed any .NET Framework on my Windows installation, and I am just using the default ones present in Windows 11. I believe there is something wrong with your Windows installation. Are you using one of those "Lite" versions of Windows with everything stripped out? If that is the case, then I guess that is the problem, otherwise, I am not able to reproduce the issue on my fresh Windows 11 installation. I do not think there is a problem with Rainbow itself.

**Comment by marco-calautti** [comment]
Somebody seems to had the same issue, with exactly the version of .NET Framework you are reporting, and it seems they solved the problem (which seems related to having an outdated Windows version): 
[https://answers.microsoft.com/en-us/windows/forum/all/net-framework-is-supposedly-already-installed-but/61ed16cc-4418-43ab-82a7-02001c2f9c53](https://answers.microsoft.com/en-us/windows/forum/all/net-framework-is-supposedly-already-installed-but/61ed16cc-4418-43ab-82a7-02001c2f9c53)
