### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by Brian151** [marco-calautti/Rainbow#6]
I can't recall if it was always like this, but the GUI is a tad annoying to work with...

Selecting different "frames" and palettes is kind of a challenge, because arrow keys only work if i first click the dropdown menu before pressing the key.

Also, correct me if I'm wrong, but didn't the top menu used to display ALL the textures in the current file?
![image](https://user-images.githubusercontent.com/10995730/28545575-ba9e8a5c-7084-11e7-9a3d-3a815997c538.png)

One other concern: when exporting .nut to PNG + metadata XML (that i just delete...lol), does rainbow try to handle ALL the palettes, or just one? (assuming there are multiple palettes in the first place)

**Comment by marco-calautti** [comment]
So, what do you suggest to improve the UI?

The top menu always displayed the list of open textures inside the directory you opened via the "open folder" menu.

Yes, Rainbow supports multi-palette NUT files, and the way it supports them (which is the best way to support subsequent editing) is by exporting a grayscale version of the image along with all the palettes. Before you were wondering: No, Rainbow does not export multiple copies of the same image with different palettes applied. This is because there are multi-palette images where different regions of the same image have distinct palettes. Applying one palette to the whole image will render visible that region but will destroy the rest. So, no Rainbow will never export multi-palette nuts in that way. If you want, you can apply the palettes that rainbow exports to the grayscale image via Photoshop or some other software.

Hope I clarified everything.

**Comment by Brian151** [comment]
well, if you can make those dropdowns work via arrow keys withOUT being constantly clicked-on, that's a start. or maybe do left/right for textures and up/down for palettes? idk...

i used open file...
It makes sense with archive file types to display at least a list of everything they contain, though.

k then... and that seems like an odd way to do things, seems to me that approach kinda mitigates the size advantage of palettes, assuming that's why use them. as for photoshop: why does everyone immediately suggest that for everything... what are some games with multi-palettes, anyways? from what i can tell, sf: assault uses none or single palettes in all textures.

i think so...
Do my UI suggestions make sense to you?

**Comment by marco-calautti** [comment]
Everyone suggests using Photoshop because that's the right tool for this kind of job. Reimplementing features found in Photoshop or any other graphics editor in Rainbow would just be a waste of time and will not be in any way near to what professional tools offer.

Wanted to let you know that I implemented a shortcut system for moving forward and backward with the frames and palettes. Jus download the dev build from the main page as usual.

**Comment by Brian151** [comment]
My problem is photoshop is expensive, and there's too much justification to use it basically for small tasks that don't REQUIRE a fancy photo editor to accomplish, but rather are in a lock-down scenario where it's the only option. I don't mind professional tools exist (although their price tags are factually WAY higher than is reasonable) , but they should be separate from stuff like palette-swapping. Photoshop is recommended for stuff you just shouldn't need to buy or pirate a full image editing suite to accomplish. I could write a program for free that'd do the same. It could be specialized just for paletted graphics (meaning it'd do stuff PS doesn't without maybe plugins, if even that), and it'd run a lot faster than PS does, and wouldn't have a huge clunky interface to find stuff. It'd also be a smaller file size (well, GIMP is worse for UI... but PS still isn't great) I could probably even do this task in TiledGDD, but, IMO, TiledGDD falls short in so many ways... Just saying.

ok... will do later
I'm doing SO many things right now...

Looks good. I see you used the "UNSPEAKABLE!" table-in-table layout... lol
For this, though, that makes sense.
I'll take a closer look later maybe...

Sorry for late reply!

**Comment by marco-calautti** [comment]
I said Photoshop just to pinpoint the fact that such tasks should not be implemented in Rainbow. There are plenty of free solutions: GIMP, Paint.net, Pinta, to name a few. Anyway, this is not the right place to discuss such topics. Glad to see my changes are ok. Will close this issue then.
